name: Coverage

on:
  push:
    branches:
      - main

env:
  GO111MODULE: on
  PROXY_ENABLED: false

jobs:
  generate-coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate coverage report
        run: go test -coverprofile coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.out
          name: codecov-krane
          fail_ci_if_error: true
          verbose: true
